generatorName: ruby
ignoreFileOverride: ".openapi-generator-ignore"
templateDir: "template"
httpUserAgent: "ruby-sdk-bmc/1.0.0-SNAPSHOT"
additionalProperties:
  gemVersion: "1.0.0-SNAPSHOT"
  gemLicense: "MPL-2.0"